spring:
  application:
    name: weather-music-service

server:
  port: 8083

eureka:
  instance:
    #hostname: localhost
    #metadataMap:
      #instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    preferIpAddress: true
    #leaseRenewalIntervalInSeconds: 5
    #lease-expiration-duration-in-seconds: 5
  client:
    #registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/