spring:
  application:
    name: weather-music-service

server:
  port: 8083

eureka:
  instance:
    preferIpAddress: true
    hostname: localhost
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
food:
  openWeatherURI: http://api.openweathermap.org/data/2.5/weather?units=metric&lang=pt&APPID=
  openWeatherToken: 
  
  spotifyOAuthURI: https://accounts.spotify.com/api/token
  spotifyClientId: 
  spotifyClientSecret: 
  spotifyPlaylistsURI: https://api.spotify.com/v1/browse/categories/{genre}/playlists?country=BR&limit=1