spring:
  application:
    name: client

server:
  port: 8084
  
feign:
  hystrix:
    enabled: false

eureka:
  instance:
    preferIpAddress: true
    hostname: localhost
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
  client:    
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true